### ISSUE TITLE
expand to report different years of census block groups

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/census_block_group#1]
include argument of "year" that can be set to 2000, 2010, etc

make sure to include a default year of 2010

**Comment by cole-brokamp** [comment]
also make sure to name variable with year in the name

**Comment by cole-brokamp** [comment]
https://github.com/degauss-org/census_block_group/blob/81a7275ecf40a7e5053401516f14696077a319ae/census_block_group.R#L34

add `_2010` here

**Comment by erikarasnick** [comment]
done, but argument doesn't currently default to 2010

**Comment by cole-brokamp** [comment]
great!  so since we are using `docopt` does this provide a useful error message if we try to run the container without specifying a year?

**Comment by cole-brokamp** [comment]
![image](https://user-images.githubusercontent.com/4367617/79506844-a97d3100-8004-11ea-842e-016ca68a4d83.png)

I think that's good! ^^^
