### ISSUE TITLE
Error when input CSV contains large number of rows with missing lat/lon

### ISSUE THREAD

**Issue by sarasunsh** [degauss-org/census_block_group#10]
Hello! I'm encountering an issue where a large number of rows with null values for the lat & lon columns => failure of the census-block encoding. In particular, this seems to happen if the number of consecutive null rows exceeds 1000. 

In other words, if the input CSV looks like this:
```
user_id,lat,lon,precision,score
1,"","","",""
2,"","","",""
3,"","","",""
.......
1000,"","","",""
10001,40.6,-73.9,0.85,range, 0.86
10002,39.7,-79.2,0.96,range, 0.67
```

running `docker run --rm -v $PWD:/tmp degauss/census_block_group:0.4.0 input.csv 2020` will cause the following failure:
```
── Wecome to DeGAUSS! ──────────────────────────────────────────────────────────
ℹ You are using the census_block_group container, version 0.4.0.
This container adds census block group or tract identifiers to geocoded
addresses.
For more information about the census_block_group container, visit
<https://degauss.org/census_block_group/>
For DeGAUSS troubleshooting, visit <https://degauss.org/>
To help us improve DeGAUSS, please take our user survey at
<https://redcap.link/jf4lil0n>

reading input file...

── Column specification ────────────────────────────────────────────────────────
cols(
  clientid = col_character(),
  patientid = col_character(),
  lat = col_logical(),
  lon = col_logical(),
  precision = col_logical(),
  score = col_logical()
)

Warning: 110260 parsing failures.
 row       col           expected     actual        file
1001 lat       1/0/T/F/TRUE/FALSE 46.8   'input.csv'
1001 lon       1/0/T/F/TRUE/FALSE -90.9 'input.csv'
1001 precision 1/0/T/F/TRUE/FALSE range      'input.csv'
1001 score     1/0/T/F/TRUE/FALSE 0.5        'input.csv'
1002 lat       1/0/T/F/TRUE/FALSE 43.6   'input.csv'
.... ......... .................. .......... ...........
See problems(...) for more details.

Warning messages:
1: In min(cc[[1]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
2: In min(cc[[2]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In max(cc[[1]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
4: In max(cc[[2]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

loading census shape files...

finding containing geography for each point...
Error: Join columns must be present in data.
✖ Problem with `.row`.
Backtrace:
    █
 1. ├─left_join(raw_data, d, by = ".row") %>% select(-.row)
 2. ├─dplyr::select(., -.row)
 3. ├─dplyr::left_join(raw_data, d, by = ".row")
 4. └─dplyr:::left_join.data.frame(raw_data, d, by = ".row")
 5.   └─dplyr:::join_mutate(...)
 6.     └─dplyr:::join_cols(...)
 7.       └─dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 8.         └─dplyr:::check_join_vars(by$y, y_names)
Execution halted
```

Whereas if I run the exact same file after removing a few rows containing null lat/lon  (so that the number of consecutive null rows is less than a thousand), it will succeed. 

Any idea why there seems to be a tolerance of up to 1000?

**Comment by cole-brokamp** [comment]
Hi and thanks for the details!  Under the hood, we are using the R package `readr` to read in the CSV files:

https://github.com/degauss-org/census_block_group/blob/38ee1e31f577e7a08d98df4563b07f4e781469da/census_block_group.R#L30

This function guesses the column type based on the first 1000 rows to decrease time required to read longer files (https://readr.tidyverse.org/reference/read_delim.html). That is, the implicit default value of `guess_max` inside `readr::read_csv()` is set to 1000 inside the container when it runs.  So, once the first 1000 values of lat or lon are empty, it will assume that it is not a numeric value, which is causing the downstream problems.

I'm not sure the best way to address this -- I don't know if adding the ability to change `guess_max` outside the container would be worthwhile given that it only occurs in this circumstance where the first 1,000 rows will not have lat or lon values.  Is it possible for your workflow to remove the rows with missing lat/lon ahead of time?  Rows with missing values are removed inside the container anyway and then merged back in before writing the output data.

**Comment by sarasunsh** [comment]
@cole-brokamp Thanks so much for the quick response! That makes sense -- I'll modify my code to skip the rows (or at least sort the CSV).

**Comment by cole-brokamp** [comment]
Thank you for bringing this up, very useful as we haven't yet discovered any issues with the `readr::read_csv` defaults and this will give us something to think about in future development.
