### ISSUE TITLE
"Error in bootstrap(" Issue Running docker Process

### ISSUE THREAD

**Issue by camachop-dbhi** [degauss-org/census_block_group#12]
Hi @cole-brokamp @andrew-vancil @erikarasnick

First off, thanks for putting these packages together! 

I have been using your [geocoder](https://github.com/degauss-org/geocoder) tool to successfully generate "geocoded" datasets using the docker approach referenced in that repo's documentation and its been super helpful.

That said I am getting an error during the docker build for this [census_block_group](https://github.com/degauss-org/census_block_group) tool using the approach outlined in your documentation.

Specifically, I am trying to run the below command on the attached text file and I am getting the error listed below. 

> **Input File**: [my_address_geocoded.csv](https://github.com/degauss-org/census_block_group/files/7521454/my_address_geocoded.csv)

[IN]:
```bash
docker run --rm -v $PWD:/tmp degauss/census_block_group:0.4.0 ./test/tmp/my_address_geocoded.csv 2020
```
[OUT]:
```error
# Bootstrapping renv 0.12.5 --------------------------------------------------
* Downloading renv 0.12.5 from CRAN archive ... FAILED
Error in bootstrap(version, libpath) : failed to download renv 0.12.5
Calls: source ... eval.parent -> eval -> eval -> eval -> eval -> bootstrap
Execution halted
```

I've tried this on both a Mac and a Linux machine and I am running into this same error.

Any chance you might be able to help resolve this issue? Or at least help me determine if this is an issue on my end or something in the Dockerfile build script/process?

Happy to provide any additional issue you might need for looking into this issue 😄 

Best,

@camachop-dbhi

**Comment by cole-brokamp** [comment]
Hi @camachop-dbhi , thanks for the detailed report.  I think this has to do with how you are specifying the input file.  The input file has to be in the current working directory from which the docker call is made.  Specifying another location will confuse the container, because that path does not exist inside. Try with:

```
docker run --rm -v $PWD:/tmp degauss/census_block_group:0.4.0 my_address_geocoded.csv 2020
```

That worked for me with your example file.

**Comment by camachop-dbhi** [comment]
Hey @cole-brokamp , Thanks for the quick follow-up!

I moved the input file to the working directory of the Dockefile as you mentioned, but looks like I am still getting the same error message 😢  see the screenshot below confirming this setup and persisted error:

<img width="894" alt="terminal-error-screen-shot" src="https://user-images.githubusercontent.com/43621073/141483617-90d40efa-025c-4fae-916e-1de96c893b34.png">

**Comment by erikarasnick** [comment]
@cole-brokamp I think this could have to do with the version of renv in the lock file. (we were installing 0.13 manually in the Dockerfile first, then the lock file was trying to install 0.12.5). 

I'm working on re-building with updated version of renv and will have @camachop-dbhi try it when it's ready. I successfully ran the example file as well before changing anything, so I'm not sure why you are getting the error and we aren't.

**Comment by cole-brokamp** [comment]
@camachop-dbhi Can you run this same command in a different folder without all of the other files in there?  The files you have in there (specifically the .Rprofile) are trying to tell R in the container to use a private library inside the current working directory, when really we want to use the global R library inside the container.

renv bootstrap and installation should never have to happen on container run time -- only at container build time.  so any renv-related errors would have to do with a competing renv installation in the working directory

**Comment by cole-brokamp** [comment]
@erikarasnick Let's not change any codebase until we can reproduce the error ourselves

**Comment by camachop-dbhi** [comment]
Hey @cole-brokamp Thanks for that tip!!

Looks like running this process from a different folder did the trick!

See the screen shot below for confirmation that this resolved my issue:

<img width="778" alt="terminal-success-screen-shot" src="https://user-images.githubusercontent.com/43621073/141502757-5e7d0981-bf2a-44bf-92da-c4449b1a6d9a.png">

Thanks again for the speedy support!! 🚀 ✨ \😄/
