### ISSUE TITLE
v0.5.0 with test/my_address_file.csv produces no results for 2010 nor 2020

### ISSUE THREAD

**Issue by eaembree** [degauss-org/census_block_group#21]
Hello,

I am testing out using the census_block_group image. It doesn't appear to produce results for years 2010 and 2020. Any thoughts or assistance would be welcome, thank you. Also, the documentation says 2010 is a default but it appears to always require a year.

To reproduce this I've done the following (I am working on a Lubuntu 20.04 VM):

1.  Create a new directory (I'm using ~/Projects/tract_test)
2. cd into the directory and place a copy of the my_address_file_geocoded.csv from this repository's test directory
3. Run (per documentation) `docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/census_block_group:0.5.0 my_address_file_geocoded.csv` which produces my_address_file_geocoded_census_block_group_0.5.0_1990.csv as expected. Behavior is the same for 1970, 1980, and 2000.
4. Running the same command using either 2010 or 2020 produces only the following stdout text and no file:

```
geocoding@geocoding-lubuntu:~/Projects/tract_test$ docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/census_block_group:0.5.0 my_address_file_geocoded.csv 2020

── Welcome to DeGAUSS! ──

• You are using census_block_group, version 0.5.0
• This container returns census block group and tract
• <https://degauss.org/census_block_group>

reading input file...
* loading input file...
* converting input to sf object...
* projecting input...
loading census shape files...
finding containing geography for each point...
geocoding@geocoding-lubuntu:~/Projects/tract_test$
```

In cases of years 1970, 1980, 1990, and 2000 those lines also include the following stdout text along prior to returning to the prompt along with the file as described above:
```
✔ FINISHED! output written to
my_address_file_geocoded_census_block_group_0.5.0_1980.csv
```

Thank you,
Eric

**Comment by cole-brokamp** [comment]
Without a `FINISHED!`, this means that the process inside the container is terminating unexpectedly.  Usually, this is due to R not having enough RAM.  Could you please try to [increase the ram](https://degauss.org/troubleshooting.html#Insufficient_Memory) available to the VM?

**Comment by cole-brokamp** [comment]
Thanks also for the comment about the default year and documentation; we will fix that via #22

**Comment by eaembree** [comment]
You were correct. It was a RAM issue. My apologies. I did see that in the troubleshooting guide earlier but since the earlier years worked I somehow didn't think to try it.

The troubleshooting image shows 4GB. I think I made a bad assumption this was a recommendation and only had 4GB assigned. Monitoring memory I found running the test file for 2010 and 2020 peaks just shy of 5GB and I had only the 4GB. I only tried 1990 and 2000 but the earlier years seem to peak around 2.5GB.

Thank you very much for your guidance.

**Comment by cole-brokamp** [comment]
No apology needed!  Thanks for bringing it up!  

Also thanks for the specific numbers on memory.  I'm going to actually open this back up as a reminder to add a memory warning to the user if the avail RAM is less than 5GB and the years are 2010 or 2020 (@erikarasnick 👀 )
