### ISSUE TITLE
changing output variable names

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/census_block_group#24]
Should we change our output variable names to be: `census_block_group_id_2010` instead of `fips_block_group_id_2010` ? (and `census_tract_id_2010` instead of `fips_tract_id_2010` ?)

In `st_census_tract`, columns output are `census_tract_id` and `census_tract_vintage`, but here the output variable name changes based on which census tract vintage is input by the user.  I like this, but think we can be consistent and say "census" instead of "fips".  

I think the CODEC data will also run into this problem with the 2020 updates to census tracts, and we will use the `census_tract_id_2010` and `census_tract_id_2020` notation there too.

**Comment by cole-brokamp** [comment]
@erikarasnick -- do you see any issues with this change?  what do you think?

**Comment by erikarasnick** [comment]
I've been thinking about this too. I didn't like that I named them differently. The only potential issue I see is with the new census_merger container, since I made it to take output from census_block_group, but I could change the column name prefix there too.

**Comment by cole-brokamp** [comment]
that's right, let's do that too.
