### ISSUE TITLE
Package 'lifecycle' 1.0.3 is required error

### ISSUE THREAD

**Issue by pdjach** [degauss-org/census_block_group#27]
Hi @cole-brokamp @andrew-vancil @erikarasnick

Thanks for putting these packages together. We're using several images and these have resolved many of our geocoding issues.

Not sure if this a problem with my environment only, but got the following error using Census Block Group:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘lifecycle’ 1.0.1 is already loaded, but >= 1.0.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
The execution is halted after this message.

Had to upgrade the following 3 packages for it to work: "lifecycle" version 1.0.3; "cli" version 3.6.1, and "rlang" version 1.1.1.

Thanks,
Paulette

**Comment by cole-brokamp** [comment]
Hello -- there shouldn't need to be any R packages installed to run a DeGAUSS container.  Is this an error from trying to run a DeGAUSS docker command?  Could you please provide a minimal example that we can use to recreate the error you are seeing?  This will help us troubleshoot.  If you don't have any test data sets that you can share, you can use the one in the repository `test/` folder.
